// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: referring_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReferringType int32

const (
	ReferringType_USER ReferringType = 0
	ReferringType_POST ReferringType = 1
)

// Enum value maps for ReferringType.
var (
	ReferringType_name = map[int32]string{
		0: "USER",
		1: "POST",
	}
	ReferringType_value = map[string]int32{
		"USER": 0,
		"POST": 1,
	}
)

func (x ReferringType) Enum() *ReferringType {
	p := new(ReferringType)
	*p = x
	return p
}

func (x ReferringType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReferringType) Descriptor() protoreflect.EnumDescriptor {
	return file_referring_type_proto_enumTypes[0].Descriptor()
}

func (ReferringType) Type() protoreflect.EnumType {
	return &file_referring_type_proto_enumTypes[0]
}

func (x ReferringType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReferringType.Descriptor instead.
func (ReferringType) EnumDescriptor() ([]byte, []int) {
	return file_referring_type_proto_rawDescGZIP(), []int{0}
}

var File_referring_type_proto protoreflect.FileDescriptor

const file_referring_type_proto_rawDesc = "" +
	"\n" +
	"\x14referring_type.proto\x12\x1ecom.test.charles.shared.models*#\n" +
	"\rReferringType\x12\b\n" +
	"\x04USER\x10\x00\x12\b\n" +
	"\x04POST\x10\x01Bm\n" +
	"\x1ecom.test.charles.shared.modelsB\rUserTypeProtoP\x01Z:charles/career-break-learn/user-service-golang/proto;protob\x06proto3"

var (
	file_referring_type_proto_rawDescOnce sync.Once
	file_referring_type_proto_rawDescData []byte
)

func file_referring_type_proto_rawDescGZIP() []byte {
	file_referring_type_proto_rawDescOnce.Do(func() {
		file_referring_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_referring_type_proto_rawDesc), len(file_referring_type_proto_rawDesc)))
	})
	return file_referring_type_proto_rawDescData
}

var file_referring_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_referring_type_proto_goTypes = []any{
	(ReferringType)(0), // 0: com.test.charles.shared.models.ReferringType
}
var file_referring_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_referring_type_proto_init() }
func file_referring_type_proto_init() {
	if File_referring_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_referring_type_proto_rawDesc), len(file_referring_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_referring_type_proto_goTypes,
		DependencyIndexes: file_referring_type_proto_depIdxs,
		EnumInfos:         file_referring_type_proto_enumTypes,
	}.Build()
	File_referring_type_proto = out.File
	file_referring_type_proto_goTypes = nil
	file_referring_type_proto_depIdxs = nil
}
