// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: user_type.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserType int32

const (
	UserType_USER UserType = 0
)

// Enum value maps for UserType.
var (
	UserType_name = map[int32]string{
		0: "USER",
	}
	UserType_value = map[string]int32{
		"USER": 0,
	}
)

func (x UserType) Enum() *UserType {
	p := new(UserType)
	*p = x
	return p
}

func (x UserType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (UserType) Descriptor() protoreflect.EnumDescriptor {
	return file_user_type_proto_enumTypes[0].Descriptor()
}

func (UserType) Type() protoreflect.EnumType {
	return &file_user_type_proto_enumTypes[0]
}

func (x UserType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use UserType.Descriptor instead.
func (UserType) EnumDescriptor() ([]byte, []int) {
	return file_user_type_proto_rawDescGZIP(), []int{0}
}

var File_user_type_proto protoreflect.FileDescriptor

const file_user_type_proto_rawDesc = "" +
	"\n" +
	"\x0fuser_type.proto\x12\x1ecom.test.charles.shared.models*\x14\n" +
	"\bUserType\x12\b\n" +
	"\x04USER\x10\x00Bk\n" +
	"\x1ecom.test.charles.shared.modelsB\rUserTypeProtoZ:charles/career-break-learn/user-service-golang/proto;protob\x06proto3"

var (
	file_user_type_proto_rawDescOnce sync.Once
	file_user_type_proto_rawDescData []byte
)

func file_user_type_proto_rawDescGZIP() []byte {
	file_user_type_proto_rawDescOnce.Do(func() {
		file_user_type_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_type_proto_rawDesc), len(file_user_type_proto_rawDesc)))
	})
	return file_user_type_proto_rawDescData
}

var file_user_type_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_user_type_proto_goTypes = []any{
	(UserType)(0), // 0: com.test.charles.shared.models.UserType
}
var file_user_type_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_user_type_proto_init() }
func file_user_type_proto_init() {
	if File_user_type_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_type_proto_rawDesc), len(file_user_type_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_type_proto_goTypes,
		DependencyIndexes: file_user_type_proto_depIdxs,
		EnumInfos:         file_user_type_proto_enumTypes,
	}.Build()
	File_user_type_proto = out.File
	file_user_type_proto_goTypes = nil
	file_user_type_proto_depIdxs = nil
}
