// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: user_activity_referring.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserActivityReferring struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          ReferringType          `protobuf:"varint,1,opt,name=type,proto3,enum=com.test.charles.shared.models.ReferringType" json:"type,omitempty"`
	Id            string                 `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserActivityReferring) Reset() {
	*x = UserActivityReferring{}
	mi := &file_user_activity_referring_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivityReferring) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivityReferring) ProtoMessage() {}

func (x *UserActivityReferring) ProtoReflect() protoreflect.Message {
	mi := &file_user_activity_referring_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivityReferring.ProtoReflect.Descriptor instead.
func (*UserActivityReferring) Descriptor() ([]byte, []int) {
	return file_user_activity_referring_proto_rawDescGZIP(), []int{0}
}

func (x *UserActivityReferring) GetType() ReferringType {
	if x != nil {
		return x.Type
	}
	return ReferringType_USER
}

func (x *UserActivityReferring) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UserActivityReferring) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

var File_user_activity_referring_proto protoreflect.FileDescriptor

const file_user_activity_referring_proto_rawDesc = "" +
	"\n" +
	"\x1duser_activity_referring.proto\x12\x1ecom.test.charles.shared.models\x1a\x14referring_type.proto\"\x83\x01\n" +
	"\x15UserActivityReferring\x12A\n" +
	"\x04type\x18\x01 \x01(\x0e2-.com.test.charles.shared.models.ReferringTypeR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userIdB|\n" +
	"\x1ecom.test.charles.shared.modelsB\x1cUserActivityParticipantProtoP\x01Z:charles/career-break-learn/user-service-golang/proto;protob\x06proto3"

var (
	file_user_activity_referring_proto_rawDescOnce sync.Once
	file_user_activity_referring_proto_rawDescData []byte
)

func file_user_activity_referring_proto_rawDescGZIP() []byte {
	file_user_activity_referring_proto_rawDescOnce.Do(func() {
		file_user_activity_referring_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_activity_referring_proto_rawDesc), len(file_user_activity_referring_proto_rawDesc)))
	})
	return file_user_activity_referring_proto_rawDescData
}

var file_user_activity_referring_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_activity_referring_proto_goTypes = []any{
	(*UserActivityReferring)(nil), // 0: com.test.charles.shared.models.UserActivityReferring
	(ReferringType)(0),            // 1: com.test.charles.shared.models.ReferringType
}
var file_user_activity_referring_proto_depIdxs = []int32{
	1, // 0: com.test.charles.shared.models.UserActivityReferring.type:type_name -> com.test.charles.shared.models.ReferringType
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_activity_referring_proto_init() }
func file_user_activity_referring_proto_init() {
	if File_user_activity_referring_proto != nil {
		return
	}
	file_referring_type_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_activity_referring_proto_rawDesc), len(file_user_activity_referring_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_activity_referring_proto_goTypes,
		DependencyIndexes: file_user_activity_referring_proto_depIdxs,
		MessageInfos:      file_user_activity_referring_proto_msgTypes,
	}.Build()
	File_user_activity_referring_proto = out.File
	file_user_activity_referring_proto_goTypes = nil
	file_user_activity_referring_proto_depIdxs = nil
}
