// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.5
// source: user_activity.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type UserActivity struct {
	state              protoimpl.MessageState   `protogen:"open.v1"`
	FeedId             string                   `protobuf:"bytes,1,opt,name=feed_id,json=feedId,proto3" json:"feed_id,omitempty"`
	SubjectReferring   []*UserActivityReferring `protobuf:"bytes,2,rep,name=subject_referring,json=subjectReferring,proto3" json:"subject_referring,omitempty"`
	ObjectReferring    []*UserActivityReferring `protobuf:"bytes,3,rep,name=object_referring,json=objectReferring,proto3" json:"object_referring,omitempty"`
	ActionTextTemplate string                   `protobuf:"bytes,4,opt,name=action_text_template,json=actionTextTemplate,proto3" json:"action_text_template,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UserActivity) Reset() {
	*x = UserActivity{}
	mi := &file_user_activity_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserActivity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserActivity) ProtoMessage() {}

func (x *UserActivity) ProtoReflect() protoreflect.Message {
	mi := &file_user_activity_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserActivity.ProtoReflect.Descriptor instead.
func (*UserActivity) Descriptor() ([]byte, []int) {
	return file_user_activity_proto_rawDescGZIP(), []int{0}
}

func (x *UserActivity) GetFeedId() string {
	if x != nil {
		return x.FeedId
	}
	return ""
}

func (x *UserActivity) GetSubjectReferring() []*UserActivityReferring {
	if x != nil {
		return x.SubjectReferring
	}
	return nil
}

func (x *UserActivity) GetObjectReferring() []*UserActivityReferring {
	if x != nil {
		return x.ObjectReferring
	}
	return nil
}

func (x *UserActivity) GetActionTextTemplate() string {
	if x != nil {
		return x.ActionTextTemplate
	}
	return ""
}

var File_user_activity_proto protoreflect.FileDescriptor

const file_user_activity_proto_rawDesc = "" +
	"\n" +
	"\x13user_activity.proto\x12\x1ecom.test.charles.shared.models\x1a\x1duser_activity_referring.proto\"\x9f\x02\n" +
	"\fUserActivity\x12\x17\n" +
	"\afeed_id\x18\x01 \x01(\tR\x06feedId\x12b\n" +
	"\x11subject_referring\x18\x02 \x03(\v25.com.test.charles.shared.models.UserActivityReferringR\x10subjectReferring\x12`\n" +
	"\x10object_referring\x18\x03 \x03(\v25.com.test.charles.shared.models.UserActivityReferringR\x0fobjectReferring\x120\n" +
	"\x14action_text_template\x18\x04 \x01(\tR\x12actionTextTemplateBq\n" +
	"\x1ecom.test.charles.shared.modelsB\x11UserActivityProtoP\x01Z:charles/career-break-learn/user-service-golang/proto;protob\x06proto3"

var (
	file_user_activity_proto_rawDescOnce sync.Once
	file_user_activity_proto_rawDescData []byte
)

func file_user_activity_proto_rawDescGZIP() []byte {
	file_user_activity_proto_rawDescOnce.Do(func() {
		file_user_activity_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_activity_proto_rawDesc), len(file_user_activity_proto_rawDesc)))
	})
	return file_user_activity_proto_rawDescData
}

var file_user_activity_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_user_activity_proto_goTypes = []any{
	(*UserActivity)(nil),          // 0: com.test.charles.shared.models.UserActivity
	(*UserActivityReferring)(nil), // 1: com.test.charles.shared.models.UserActivityReferring
}
var file_user_activity_proto_depIdxs = []int32{
	1, // 0: com.test.charles.shared.models.UserActivity.subject_referring:type_name -> com.test.charles.shared.models.UserActivityReferring
	1, // 1: com.test.charles.shared.models.UserActivity.object_referring:type_name -> com.test.charles.shared.models.UserActivityReferring
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_user_activity_proto_init() }
func file_user_activity_proto_init() {
	if File_user_activity_proto != nil {
		return
	}
	file_user_activity_referring_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_activity_proto_rawDesc), len(file_user_activity_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_user_activity_proto_goTypes,
		DependencyIndexes: file_user_activity_proto_depIdxs,
		MessageInfos:      file_user_activity_proto_msgTypes,
	}.Build()
	File_user_activity_proto = out.File
	file_user_activity_proto_goTypes = nil
	file_user_activity_proto_depIdxs = nil
}
